export let SelectOptions = [
    {name: "Fruits",
     value: "fruits",
    },
    {name: "Ice Cream",
     value: "icecrem",
    },
    {name: "Fruits",
     value: "fruits",
    },
    {name: "Chicken",
     value: "chicken",
    },
    {name: "Curry",
     value: "curry",
    },
    {name: "Fish",
     value: "fish",
    },
    {name: "Rice",
     value: "rice",
    },
    {name: "Drinks",
     value: "drinks",
    },
] 